# Generated by Django 4.1.6 on 2023-02-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsendler',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='formsendler',
            name='date',
        ),
        migrations.AlterField(
            model_name='formsendler',
            name='phone_num',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
